---
title: "Summer 2021 R Workshop"
subtitle: "ModernDive"
author: "N. Paterno"
output: 
  html_document:
    css: style.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
*** 
## Welcome!

Welcome to our workshop on learning R using ModernDive! The goal of this workshop is to introduce the R language and how it is used for statistical analysis. The concepts we'll cover are (mostly) covered in our Math&146 course. The exception being multiple regression. The focus will be learning R but I'm sure there will be some talk of how to teach R. 

### Schedule:
We'll meet via Zoom on 6/29, 7/13, 7/27, 8/10 and 8/24 from 10:00 am to 11:00 am. Zoom links will be emailed out as well as posted in the Teams folder. 

Zoom sessions will be recorded and the videos will be uploaded to the Teams folder. 

### Resources:

#### Setting Up Version Control with Git and GitHub
* [For Windows](https://youtu.be/lHz-r2lJ2o8) Everything after the 5:40 mark is for another project.
* [For Mac](https://youtu.be/yfCe39JKBTE) Everything after the 4:10 mark is for another project.

#### Reading & Tutorials:
* [R for Data Science](https://r4ds.had.co.nz): This is another text that is a great resource for those new to R. 
* [R4DS Online Learning Community](https://www.rfordatasci.com): This is a community that was born from a book club for the above text. There is a very active Slack for this group as well as the website. 
* [learnR](https://rstudio.github.io/learnr/): These tutorials can be followed online or in RStudio.
* [Project-oriented Workflow](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) This article gives a few great examples of why a project-oriented workflow is very useful and efficient. 

#### Streaming:

* [#SLICED](https://www.notion.so/SLICED-Show-c7bd26356e3a42279e2dfbafb0480073): This is a live, data science competition. For those who are more visual, this is a great way to watch people who use R on a regular basis and see their process. 
* [Jesse Mostipak](https://www.twitch.tv/kierisi): Jesse streams a few times per week on Twitch.
* [Moriah Taylor](https://www.twitch.tv/moriah_streamR): Moriah streams once a week to work on her TidyTuesday projects. 
* [David Robinson](https://www.youtube.com/channel/UCeiiqmVK07qhY-wvg3IZiZQ): David usually streams once per week and has also participated in \#SLICED.
* [Julia Silge](https://www.youtube.com/channel/UCTTBgWyJl2HrrhQOOc710kA): Julia also streams her TidyTuesday projects. She usually focuses on modeling in addition to data viz. She has also been involved with \#SLICED.